/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.3
  Forc version: 0.63.1
  Fuel-Core version: 0.34.0
*/

import { Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  AbstractAddress,
  BigNumberish,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

export type GenericNestedLevelFourInput<Four> = { four: Four };
export type GenericNestedLevelFourOutput<Four> = GenericNestedLevelFourInput<Four>;
export type GenericNestedLevelOneInput<One, OneOne> = { one: GenericNestedLevelTwoInput<One>, one_one: OneOne };
export type GenericNestedLevelOneOutput<One, OneOne> = { one: GenericNestedLevelTwoOutput<One>, one_one: OneOne };
export type GenericNestedLevelThreeInput<Three> = { three: GenericNestedLevelFourInput<Three> };
export type GenericNestedLevelThreeOutput<Three> = { three: GenericNestedLevelFourOutput<Three> };
export type GenericNestedLevelTwoInput<Two> = { two: GenericNestedLevelThreeInput<Two> };
export type GenericNestedLevelTwoOutput<Two> = { two: GenericNestedLevelThreeOutput<Two> };

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "struct GenericNestedLevelOne<u8,u16>",
      "concreteTypeId": "8c9d832f70d0f67a529fde8c69ac83de791725c3010ea1647b8d62f3816abbdc",
      "metadataTypeId": 6,
      "typeArguments": [
        "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b",
        "29881aad8730c5ab11d275376323d8e4ff4179aae8ccb6c13fe4902137e162ef"
      ]
    },
    {
      "type": "u16",
      "concreteTypeId": "29881aad8730c5ab11d275376323d8e4ff4179aae8ccb6c13fe4902137e162ef"
    },
    {
      "type": "u8",
      "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
    }
  ],
  "metadataTypes": [
    {
      "type": "generic Four",
      "metadataTypeId": 0
    },
    {
      "type": "generic One",
      "metadataTypeId": 1
    },
    {
      "type": "generic OneOne",
      "metadataTypeId": 2
    },
    {
      "type": "generic Three",
      "metadataTypeId": 3
    },
    {
      "type": "generic Two",
      "metadataTypeId": 4
    },
    {
      "type": "struct GenericNestedLevelFour",
      "metadataTypeId": 5,
      "components": [
        {
          "name": "four",
          "typeId": 0
        }
      ],
      "typeParameters": [
        0
      ]
    },
    {
      "type": "struct GenericNestedLevelOne",
      "metadataTypeId": 6,
      "components": [
        {
          "name": "one",
          "typeId": 8,
          "typeArguments": [
            {
              "name": "",
              "typeId": 1
            }
          ]
        },
        {
          "name": "one_one",
          "typeId": 2
        }
      ],
      "typeParameters": [
        1,
        2
      ]
    },
    {
      "type": "struct GenericNestedLevelThree",
      "metadataTypeId": 7,
      "components": [
        {
          "name": "three",
          "typeId": 5,
          "typeArguments": [
            {
              "name": "",
              "typeId": 3
            }
          ]
        }
      ],
      "typeParameters": [
        3
      ]
    },
    {
      "type": "struct GenericNestedLevelTwo",
      "metadataTypeId": 8,
      "components": [
        {
          "name": "two",
          "typeId": 7,
          "typeArguments": [
            {
              "name": "",
              "typeId": 4
            }
          ]
        }
      ],
      "typeParameters": [
        4
      ]
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "arg1",
          "concreteTypeId": "8c9d832f70d0f67a529fde8c69ac83de791725c3010ea1647b8d62f3816abbdc"
        }
      ],
      "name": "generic",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const storageSlots: StorageSlot[] = [];

export class ContractDeepGenericsInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    generic: FunctionFragment;
  };
}

export class ContractDeepGenerics extends Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: ContractDeepGenericsInterface;
  declare functions: {
    generic: InvokeFunction<[arg1: GenericNestedLevelOneInput<BigNumberish, BigNumberish>], void>;
  };

  constructor(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
