/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.3
  Forc version: 0.63.3
  Fuel-Core version: 0.34.0
*/

import { ContractFactory, decompressBytecode } from "fuels";
import type { Provider, Account, DeployContractOptions, DeployContractResult } from "fuels";

import { ContractTuple } from "./ContractTuple";

const bytecode = decompressBytecode("H4sIAAAAAAAAA5WSP0vDQBjGn8Rqq9Nh63I6dLBQJwtWB0FoSUNa29LbdDC2IkV0EAnSxaUfQQX/jP0IGfwAGTtmdMxowUAHhUqH+iZpKGgrGDjuvTy/973n7l7ez+AakOF/clcfWRIbjbx/4O8Cd8CbrvQllofFCw0YRVkwNdHmPYbkYAuHQ0cWQydC/AU/sDFmijOYE67Z0EsMRgUxYixRM3N1l8XqbnLRKICl3WxOaOYr6SytvVgUN8JYVxmIzxC/QHyUNGYUSVOzbVE2uz5XopoUE5esu4gYOURpnheKKQxBen7bq3Hlx9UV8F7mp0fF80hMO2DmpzG7vGYjTv7j5IlXgFYBa+Sn43tQ160pZ98b1zX/qJvlis/cBkxqGrPKyzY2qonlVgUSrZeO8gK0t3Ws0pv93neT54AUDbqLmx2aH4C5x1jwvlzpgGsO9DytP2l8MTyT9kTM/sBnoyFLvcBC3r93N9LmiunlSl7uvadP8qP/yPf3npEvTbw64B+eR4SM5DEa9epZ87JpnJ8GbQy58w2O3GTD2AIAAA==");

export class ContractTupleFactory extends ContractFactory {

  static readonly bytecode = bytecode;

  constructor(accountOrProvider: Account | Provider) {
    super(bytecode, ContractTuple.abi, accountOrProvider);
  }

  static async deploy (
    wallet: Account,
    options: DeployContractOptions = {}
  ): Promise<DeployContractResult<ContractTuple>> {
    const factory = new ContractTupleFactory(wallet);

    return factory.deploy({
      storageSlots: ContractTuple.storageSlots,
      ...options,
    });
  }
}
